<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Payslip</title>
    <style>
        body { font-family: sans-serif; color: #333; font-size: 14px; }
        .container { width: 100%; padding: 20px; }
        
        .header { text-align: center; border-bottom: 2px solid #312e81; padding-bottom: 10px; margin-bottom: 20px; }
        .header h1 { margin: 0; color: #312e81; text-transform: uppercase; }
        .header p { margin: 5px 0; color: #666; font-size: 12px; }

        .info-table { width: 100%; margin-bottom: 20px; }
        .info-table td { padding: 5px; }
        .label { font-weight: bold; color: #555; }

        .salary-table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        .salary-table th { background-color: #e5e7eb; padding: 10px; text-align: left; border: 1px solid #ccc; }
        .salary-table td { padding: 10px; border: 1px solid #ccc; }
        .text-right { text-align: right; }
        .total-row { background-color: #312e81; color: white; font-weight: bold; }

        .footer { position: fixed; bottom: 0; left: 0; right: 0; text-align: center; font-size: 10px; color: #aaa; }
    </style>
</head>
<body>
    <div class="container">
        
        <div class="header">
    <!-- LOGO HERE -->
    <img src="{{ public_path('images/logo.png') }}" style="height: 80px; width: auto; margin-bottom: 10px;">
    
    <h1>M7 PCIS</h1>
    <p>OFFICIAL PAYSLIP DOCUMENT</p>
</div>

        <table class="info-table">
            <tr>
                <td class="label">Employee Name:</td>
                <!-- Use optional() to prevent crash if user is missing -->
                <td>{{ optional($payroll->employee->user)->name ?? 'Unknown' }}</td>
                
                <td class="label">Date Generated:</td>
                <td>{{ \Carbon\Carbon::parse($payroll->pay_date)->format('M d, Y') }}</td>
            </tr>
            <tr>
                <td class="label">Position:</td>
                <td>{{ $payroll->employee->position ?? 'N/A' }}</td>
                
                <td class="label">Payroll ID:</td>
                <td>#{{ str_pad($payroll->id, 5, '0', STR_PAD_LEFT) }}</td>
            </tr>
        </table>

        <table class="salary-table">
            <thead>
                <tr>
                    <th>Description</th>
                    <th class="text-right">Amount</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Basic Salary / Gross Pay</td>
                    <td class="text-right">${{ number_format($payroll->gross_salary, 2) }}</td>
                </tr>
                <tr>
                    <td>Deductions (Tax, SS, PhilHealth)</td>
                    <td class="text-right" style="color: #dc2626;">- ${{ number_format($payroll->deductions, 2) }}</td>
                </tr>
                <tr class="total-row">
                    <td>NET SALARY (Take Home)</td>
                    <td class="text-right">${{ number_format($payroll->net_salary, 2) }}</td>
                </tr>
            </tbody>
        </table>

        <br>
        <p><strong>Status:</strong> <span style="color: green;">PAID</span></p>

        <div class="footer">
            System Generated by M7 PCIS Payroll System. Valid without signature.
        </div>

    </div>
</body>
</html>